In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.2-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=2.3.3 in /Users/vinaykarakavalasa/Complete-Python-Bootcamp/env/lib/python3.14/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/vinaykarakavalasa/Complete-Python-Bootcamp/env/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/vinaykarakavalasa/Complete-Python-Bootcamp/env/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.2-cp314-cp314-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 23.3 MB/s  0:00:00 eta 0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.2

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [5]:
import pandas as pd
data = [10,20,30,40,50]
series = pd.Series(data, index=['a','b','c','d','e']) #can customize the index of the series
print(series)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [6]:
import pandas as pd
data = [10,20,30,40,50]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [10]:
#DataFrame creation
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
print(df.head()) #displays the first few rows of the DataFrame
print("\nDataFrame Info:   ")
print(df['Name'])

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago

DataFrame Info:
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

In [12]:
import pandas as pd
df = pd.read_csv('sales_data.csv')
df.head(3)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card

In [14]:
#accessing the data from the dataframe
type(df['Date'])

pandas.Series

In [15]:
#also go through implementing iloc and loc functionalities in pandas for accessing the data in the dataframe.
#iloc is used for integer-location based indexing, while loc is used for label-based indexing.
#iloc is fast and efficient for accessing data based on integer positions, while loc is more flexible and allows for accessing data based on labels, which can be more intuitive in certain cases.

In [16]:
df.head(3)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card

In [22]:
result = df.loc[0:0]
print(result, "\n")

   Transaction ID        Date Product Category   Product Name  Units Sold  \
0           10001  2024-01-01      Electronics  iPhone 14 Pro           2

   Unit Price  Total Revenue         Region Payment Method
0      999.99        1999.98  North America    Credit Card

In [23]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Vinay', 'Rahul', 'Sneha', 'Ankit'],
    'Age': [25, 30, 28, 22],
    'Salary': [50000, 60000, 55000, 40000]
}, index=['a', 'b', 'c', 'd'])

print(df)

    Name  Age  Salary
a  Vinay   25   50000
b  Rahul   30   60000
c  Sneha   28   55000
d  Ankit   22   40000

In [27]:
print(df.loc['a']) #prints the entire data related to index 'a'
print("\n")
print(df.loc['a':'b','Name':'Salary'])

Name      Vinay
Age          25
Salary    50000
Name: a, dtype: object


    Name  Age  Salary
a  Vinay   25   50000
b  Rahul   30   60000

In [49]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Vinay', 'Rahul', 'Sneha', 'Ankit'],
    'Age': [25, 30, 28, 22],
    'Salary': [50000, 60000, 55000, 40000]
}, index=[0,1,2,3])

print(df)

    Name  Age  Salary
0  Vinay   25   50000
1  Rahul   30   60000
2  Sneha   28   55000
3  Ankit   22   40000

In [29]:
print(df.iloc[0])

Name      Vinay
Age          25
Salary    50000
Name: 0, dtype: object

In [31]:
print(df.iloc[0:3, 0:3])

    Name  Age  Salary
0  Vinay   25   50000
1  Rahul   30   60000
2  Sneha   28   55000

In [32]:
df

    Name  Age  Salary
0  Vinay   25   50000
1  Rahul   30   60000
2  Sneha   28   55000
3  Ankit   22   40000

In [35]:
salaried_df = df[df['Salary']>=50000]
print(salaried_df)

    Name  Age  Salary
0  Vinay   25   50000
1  Rahul   30   60000
2  Sneha   28   55000

In [36]:
print(df)

    Name  Age  Salary
0  Vinay   25   50000
1  Rahul   30   60000
2  Sneha   28   55000
3  Ankit   22   40000

In [38]:
print(df.at[0,'Salary'])

50000

In [45]:
df['Designation'] = ['Doctor', 'Engineer', 'Artist', 'Teacher']
df

    Name  Age  Salary Designation
0  Vinay   25   50000      Doctor
1  Rahul   30   60000    Engineer
2  Sneha   28   55000      Artist
3  Ankit   22   40000     Teacher

In [46]:
df = df.drop(columns =['Designation'])
df

    Name  Age  Salary
0  Vinay   25   50000
1  Rahul   30   60000
2  Sneha   28   55000
3  Ankit   22   40000

In [50]:
df = df.drop('Age', axis=1, inplace=True)
print(df)

None

In [51]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Vinay', 'Rahul', 'Sneha', 'Ankit'],
    'Age': [25, 30, 28, 22],
    'Salary': [50000, 60000, 55000, 40000]
}, index=[0,1,2,3])

print(df)

    Name  Age  Salary
0  Vinay   25   50000
1  Rahul   30   60000
2  Sneha   28   55000
3  Ankit   22   40000

In [55]:
df.drop('Salary', axis=1, inplace=True) #without assigning it to a new variable, the original dataframe will be modified and the 'Salary' column will be removed permanently.
#this is happening only due to the inplace parameter being set to True.
print(df)

KeyError: "['Salary'] not found in axis"

In [56]:
df.drop('Age', axis=1)
df

    Name  Age
0  Vinay   25
1  Rahul   30
2  Sneha   28
3  Ankit   22

In [57]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Vinay', 'Rahul', 'Sneha', 'Ankit'],
    'Age': [25, 30, 28, 22],
    'Salary': [50000, 60000, 55000, 40000]
}, index=[0,1,2,3])

print(df)
print(df.describe())

    Name  Age  Salary
0  Vinay   25   50000
1  Rahul   30   60000
2  Sneha   28   55000
3  Ankit   22   40000
         Age        Salary
count   4.00      4.000000
mean   26.25  51250.000000
std     3.50   8539.125638
min    22.00  40000.000000
25%    24.25  47500.000000
50%    26.50  52500.000000
75%    28.50  56250.000000
max    30.00  60000.000000